#48: Added sensor for year-to-date consumption.
JonasPed/homeassistant-eloverblik pull request #53
Opened 2022-09-13 11:19 UTC by runemoennike

Adds a new sensor that shows the total consumption for the current year.

2022-09-26 18:39 UTC, JonasPed requested changes

2022-09-26 18:39 UTC, JonasPed commented on custom_components/eloverblik/__init__.py
> +        if self._day_data != None:
Should this not be _year_data != None?

2022-09-27 09:06 UTC, runemoennike commented on custom_components/eloverblik/__init__.py
> +        if self._day_data != None:
Yes, thanks!

2022-09-27 18:13 UTC, JonasPed approved these changes

2022-09-27 18:13 UTC, merged