Added support for long-term statistics
JonasPed/homeassistant-eloverblik pull request #69
Opened 2023-01-12 09:03 UTC by MartinSchmidt

This PR adds a new sensor `sensor.eloverblik_energy_statistic`, this sensor uses `async_import_statistics` functionality to import long-term statistics into HomeAssistant.

The statistics are inserted at the correct point in time and amount, also tested around summer/winter time. 

The sensor always has an unknown value as to not make the recorder log the value, but one can still use its long-term statistics.

I have extended the readme with example on how to use it on a dashboard.

2023-01-16 14:33 UTC, MartinSchmidt commented
Just discovered another small bug (a missing if statement) , I will get it fix one of the following days.

2023-01-21 18:45 UTC, MartinSchmidt commented
I fixed the bug, and has been running for the better part of a week without issues

@JonasPed  will you take a look at this PR 🙂

2023-01-23 21:02 UTC, JonasPed commented
Thanks. I will take a look at it and test it as soon as I have a few hours of spare time.

2023-01-25 16:51 UTC, frenzeldk commented
After reading through the changes and applying the patch to my installation and having it run for a while I have not noticed any issues. For obvious reasons I have not tested the summer/winter time functionality.

2023-01-26 20:50 UTC, JonasPed requested changes
Look very good. Just a couple of minor comments. 

Would it not be an idea to hide the statistics sensor by default? Hidden sensors is still updated they are just not shown in the UI by default. I think this can be done by adding a property named entity_registry_visible_default and let it return False. This way we will hide the sensor that always reads Unknown.

2023-01-31 20:09 UTC, JonasPed commented
It have been running in a test setup for a couple of days now and every night/morning I see something like below. Will turn on some debugging to get further details. 

```
2023-01-31 05:35:56.647 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eloverblik/sensor.py", line 206, in _update_data
    await self._insert_statistics(data, last_stat)
  File "/config/custom_components/eloverblik/sensor.py", line 226, in _insert_statistics
    number_of_hours = len(time_series._metering_data)
TypeError: object of type 'NoneType' has no len()

```

2023-02-03 18:45 UTC, MartinSchmidt commented
I will have a look at it during the weekend, and also the vommenes you wrote.

2023-02-05 09:57 UTC, MartinSchmidt commented on README.md
> +> **_NOTE:_**  The data will be between 1 and 3 days of delay, depending on your DSO.
I have changed the description, hope it is more understandable.

2023-02-05 09:58 UTC, MartinSchmidt commented on custom_components/eloverblik/manifest.json
> +  "version": "0.5.0",
I have reverted the version, i though it was supposed to follow the versions you create her on github.

2023-02-05 09:59 UTC, MartinSchmidt commented
> It have been running in a test setup for a couple of days now and every night/morning I see something like below. Will turn on some debugging to get further details.
> 
> ```
> 2023-01-31 05:35:56.647 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/eloverblik/sensor.py", line 206, in _update_data
>     await self._insert_statistics(data, last_stat)
>   File "/config/custom_components/eloverblik/sensor.py", line 226, in _insert_statistics
>     number_of_hours = len(time_series._metering_data)
> TypeError: object of type 'NoneType' has no len()
> ```

I have added some extra validation, it should no longer throw the error, but I will keep an eye on my local instance the next couple of days.

2023-02-06 19:03 UTC, JonasPed commented
Looks great. I will update my own installation and let it run for a few days before merging.

2023-02-10 19:25 UTC, merged

2023-02-10 19:25 UTC, JonasPed commented
Thanks